[build-system]
requires = [
    "scikit-build-core>=0.3.3",
    "pybind11>=2.5.0",
    "cmake>=3.15",
    "ninja",
]
build-backend = "scikit_build_core.build"

[project]
name = "fdcomp"
version = "0.2.1"
authors = [
    {name = "Luis Denninger", email = "Luis0512@web.de"}
]
maintainers = [
    {name = "Luis Denninger", email = "Luis0512@web.de"}
]
license = "Apache-2.0"
description = "A python library for efficient depth compression to increase throughput and minimize memory footprint"
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.6"
dependencies = [
    "numpy>=1.15.0",
    "termcolor>=1.1.0",
    "gnuplotlib>=0.31.0",
    "matplotlib>=3.0.0",
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.11",
]
[project.optional-dependencies]
# keep test dependencies only for pytest
test = [
    "pytest",
    "pytest-cov",
]


[tool.scikit-build]
cmake.verbose = true
logging.level = "INFO"
cmake.args = ["-DCMAKE_BUILD_TYPE=Release"]
